### ISSUE TITLE
Patchers aborts with "System.NullReferenceException: Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by Arr1x** [Wolfman5750/Z-Floor-Patcher#2]
Newest Synthesis and mutagen version, patcher is set to match. 

```
[413.8] Found Object out of bounds  Z: -46354,863
[413.8] System.NullReferenceException: Object reference not set to an instance of an object.
[413.8]    at z_FloorPatcher.z_FloorPatcher.RunPatch(IPatcherState`2 state) in C:\Users\Arrix\AppData\Local\Temp\Synthesis\2gav00br.sfl\Git\jfd0djxg.jfp\Runner\ZFloorPatcher\Z-FloorPatcher.cs:line 39
[413.8]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 97
[413.8] --- End of stack trace from previous location ---
[413.8]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 548
[413.8]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 447
[413.8]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 410
[818.6] No extra data to consider
```

**Comment by Noggog** [comment]
This was fixed in Nov 2022, I believe.  Can probably close
